### ISSUE TITLE
Naive installation leads to heap corruption on shutdown

### ISSUE THREAD

**Issue by Nopey** [Joshua-Ashton/VAudio-MiniMP3#1]
It might be worth mentioning in README that some versions of snd_dma.cpp may corrupt the heap by deleting the `vaudio` pointer to s_VAudio.
Thanks!

**Comment by misyltoad** [comment]
I will implement a mitigation for this, thanks!

**Comment by misyltoad** [comment]
Should be fixed now, thanks!
